"""add table goods_in_carts

Revision ID: 01b7aa5a3daa
Revises: cf67f8000aa0
Create Date: 2021-11-11 13:07:58.384135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b7aa5a3daa'
down_revision = 'cf67f8000aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_in_carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_in_carts')
    # ### end Alembic commands ###
