"""add table goods_in_carts

Revision ID: 5aa60c8f36e4
Revises: ab34d1b28a18
Create Date: 2021-11-10 20:31:50.807765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa60c8f36e4'
down_revision = 'ab34d1b28a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
