"""patch goods

Revision ID: ab34d1b28a18
Revises: e3b227b7b297
Create Date: 2021-11-10 19:58:22.393805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab34d1b28a18'
down_revision = 'e3b227b7b297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('category_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
