"""patch transactions

Revision ID: e3b227b7b297
Revises: 4606a467993f
Create Date: 2021-11-10 19:51:48.965903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b227b7b297'
down_revision = '4606a467993f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_ip', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'user_ip')
    # ### end Alembic commands ###
